# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!

# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: false

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# rainbow!
rainbow_banner: true
rainbow_banner_colors:
  - '#e50000'
  - '#ff8d00'
  - '#ffee00'
  - '#008121'
  - '#004cff'
  - '#760188'
# choose from [auto, always]
rainbow_banner_shown: auto
# Pride Month by default
rainbow_banner_month: 6

# TOC - table of contents
toc: true
toc_max_depth: 2

# scroll reveal (https://scrollrevealjs.org/) - animating elements as they enter/leave the viewport
scroll_reveal: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Blog
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Tags: /tags
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/geekwen
    Codepen: https://codepen.io/geekwen
    #Patreon: https://www.patreon.com/MrWillCom
    #Mastodon: https://noc.social/@MrWillCom
    #Discord: https://discord.gg/UKuFDjcfY8
    Search: /search

# footer items
#footer:
  # the title
  #blog:
    # the items after the title, display as links
    #blog: /
    #archives: /archives
    #tags: /tags
    #search: /search
    #resume: /resume
    #about: /about
    #rss: /atom.xml
  # also the title
  #projects:
    # the items
    # rsa cli: https://github.com/mrwillcom/rsa-cli
    # hexo theme cupertino: https://github.com/mrwillcom/hexo-theme-cupertino
    # a calendar: https://github.com/mrwillcom/a-calendar
    # auto mirroring bucket: https://github.com/mrwillcom/auto-mirroring-bucket
  # the title
  #Me:
    # items
    #GitHub: https://github.com/geekwen
    #CodePen: https://codepen.io/geekwen
    #Email: mailto:sundingwen@foxmail.com

# footer extra description
# footer_extra_description: something will be shown at the bottom of the footer

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# search
# based on [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)
search: true
search_path: search.json

# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!
